/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PwaCameraModalInstance {}
  interface PwaCameraModalInstanceAttributes extends StencilHTMLAttributes {
    'onOnPhoto'?: (event: CustomEvent) => void;
  }

  interface PwaCameraModal {
    'dismiss': () => Promise<void>;
    'present': () => Promise<void>;
  }
  interface PwaCameraModalAttributes extends StencilHTMLAttributes {
    'onOnPhoto'?: (event: CustomEvent) => void;
  }

  interface PwaCamera {
    'facingMode': string;
    'onPhoto': (e: any) => void;
  }
  interface PwaCameraAttributes extends StencilHTMLAttributes {
    'facingMode'?: string;
    'onPhoto'?: (e: any) => void;
  }

  interface PwaToast {
    'duration': number;
    'message': string;
  }
  interface PwaToastAttributes extends StencilHTMLAttributes {
    'duration'?: number;
    'message'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PwaCameraModalInstance': Components.PwaCameraModalInstance;
    'PwaCameraModal': Components.PwaCameraModal;
    'PwaCamera': Components.PwaCamera;
    'PwaToast': Components.PwaToast;
  }

  interface StencilIntrinsicElements {
    'pwa-camera-modal-instance': Components.PwaCameraModalInstanceAttributes;
    'pwa-camera-modal': Components.PwaCameraModalAttributes;
    'pwa-camera': Components.PwaCameraAttributes;
    'pwa-toast': Components.PwaToastAttributes;
  }


  interface HTMLPwaCameraModalInstanceElement extends Components.PwaCameraModalInstance, HTMLStencilElement {}
  var HTMLPwaCameraModalInstanceElement: {
    prototype: HTMLPwaCameraModalInstanceElement;
    new (): HTMLPwaCameraModalInstanceElement;
  };

  interface HTMLPwaCameraModalElement extends Components.PwaCameraModal, HTMLStencilElement {}
  var HTMLPwaCameraModalElement: {
    prototype: HTMLPwaCameraModalElement;
    new (): HTMLPwaCameraModalElement;
  };

  interface HTMLPwaCameraElement extends Components.PwaCamera, HTMLStencilElement {}
  var HTMLPwaCameraElement: {
    prototype: HTMLPwaCameraElement;
    new (): HTMLPwaCameraElement;
  };

  interface HTMLPwaToastElement extends Components.PwaToast, HTMLStencilElement {}
  var HTMLPwaToastElement: {
    prototype: HTMLPwaToastElement;
    new (): HTMLPwaToastElement;
  };

  interface HTMLElementTagNameMap {
    'pwa-camera-modal-instance': HTMLPwaCameraModalInstanceElement
    'pwa-camera-modal': HTMLPwaCameraModalElement
    'pwa-camera': HTMLPwaCameraElement
    'pwa-toast': HTMLPwaToastElement
  }

  interface ElementTagNameMap {
    'pwa-camera-modal-instance': HTMLPwaCameraModalInstanceElement;
    'pwa-camera-modal': HTMLPwaCameraModalElement;
    'pwa-camera': HTMLPwaCameraElement;
    'pwa-toast': HTMLPwaToastElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
