/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@ionic/core';


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  ActionSheetPWA as IonPwaActionSheet
} from './components/action-sheet/action-sheet';

declare global {
  interface HTMLIonPwaActionSheetElement extends IonPwaActionSheet, HTMLStencilElement {
  }
  var HTMLIonPwaActionSheetElement: {
    prototype: HTMLIonPwaActionSheetElement;
    new (): HTMLIonPwaActionSheetElement;
  };
  interface HTMLElementTagNameMap {
    "ion-pwa-action-sheet": HTMLIonPwaActionSheetElement;
  }
  interface ElementTagNameMap {
    "ion-pwa-action-sheet": HTMLIonPwaActionSheetElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ion-pwa-action-sheet": JSXElements.IonPwaActionSheetAttributes;
    }
  }
  namespace JSXElements {
    export interface IonPwaActionSheetAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  CameraModalPWA as IonPwaCameraModal
} from './components/camera-modal/camera-modal';

declare global {
  interface HTMLIonPwaCameraModalElement extends IonPwaCameraModal, HTMLStencilElement {
  }
  var HTMLIonPwaCameraModalElement: {
    prototype: HTMLIonPwaCameraModalElement;
    new (): HTMLIonPwaCameraModalElement;
  };
  interface HTMLElementTagNameMap {
    "ion-pwa-camera-modal": HTMLIonPwaCameraModalElement;
  }
  interface ElementTagNameMap {
    "ion-pwa-camera-modal": HTMLIonPwaCameraModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ion-pwa-camera-modal": JSXElements.IonPwaCameraModalAttributes;
    }
  }
  namespace JSXElements {
    export interface IonPwaCameraModalAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  CameraPWA as IonPwaCamera
} from './components/camera/camera';

declare global {
  interface HTMLIonPwaCameraElement extends IonPwaCamera, HTMLStencilElement {
  }
  var HTMLIonPwaCameraElement: {
    prototype: HTMLIonPwaCameraElement;
    new (): HTMLIonPwaCameraElement;
  };
  interface HTMLElementTagNameMap {
    "ion-pwa-camera": HTMLIonPwaCameraElement;
  }
  interface ElementTagNameMap {
    "ion-pwa-camera": HTMLIonPwaCameraElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ion-pwa-camera": JSXElements.IonPwaCameraAttributes;
    }
  }
  namespace JSXElements {
    export interface IonPwaCameraAttributes extends HTMLAttributes {
      facingMode?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
